name: Fetch from usaco-problems
on: workflow_dispatch

jobs:
  update_problems:
    name: Update problems
    runs-on: ubuntu-latest
    steps:
      - name: Checkout usaco-guide
        uses: actions/checkout@v2
      - name: Checkout usaco-problems
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/usaco-problems
          path: usaco-problems
      - name: Build list of problem ids
        run: |
          git branch auto
          git checkout auto
          yarn
          yarn develop &
          sleep 20
          pkill -f 'yarn develop'
          ls
      - name: Add new problems
        run: |
          npx ts-node --skipProject usaco-problems/add_problems ../ids.log ../content/extraProblems.json
          git add .
          git config --global user.name usaco-autofetch[bot]
          git config --global user.email usaco-autofetch[bot]@users.noreply.github.com
          git commit -m 'problem auto-updates'
          git push -f origin auto
          gh pr close $(gh pr list --json number --jq '.[0].number' --author 'usaco-autofetch[bot]') || true
          gh pr create --title 'Problem auto-updates' -F usaco-problems/out/report.txt
        env:
          GH_TOKEN: ${{ github.token }}
