name: Fetch from usaco-problems
on: workflow_dispatch

jobs:
  update_problems:
    name: Update problems
    runs-on: ubuntu-latest
    steps:
      - name: Checkout usaco-guide
        uses: actions/checkout@v2
      - name: Checkout usaco-problems
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/usaco-problems
          path: usaco-problems
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Build list of problem ids
        run: |
          yarn
          yarn build
          echo 'ids.log tail:'
          cat -b ids.log | tail -n 10
      - name: Add new problems
        run: |
          npx ts-node --skipProject usaco-problems/add_problems ../ids.log ../content/extraProblems.json
          git stash
          export pr_number=$(gh pr list --author 'usaco-autofetch[bot]' --json number --jq '.[0].number')
          if [ -z "$pr_number" ]
          then
            git checkout -b auto
            git push -f origin auto
            gh pr create --title 'Problem auto-updates' -F usaco-problems/out/report.txt
          else
            git checkout origin/auto
            git switch -c auto
            gh pr edit $pr_number -F usaco-problems/out/report.txt
          fi
          git stash pop
          git add .
          git config --global user.name usaco-autofetch[bot]
          git config --global user.email usaco-autofetch[bot]@users.noreply.github.com
          git commit -m 'problem auto-updates'
          git push origin auto
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
